controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_base_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_base_controller:
  ros__parameters:
    left_wheel_names: ["drivewhl_l_joint"]
    right_wheel_names: ["drivewhl_r_joint"]

    wheel_separation: 0.4
    #wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.1

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal : [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]

    open_loop: true // TODO ?
    enable_odom_tf: false

    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true
    use_stamped_vel: false
    #velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0

# <gazebo>
#     <plugin name='diff_drive' filename='libgazebo_ros_diff_drive.so'>
#       <ros>
#         <namespace>/demo</namespace>
#       </ros>

#       <!-- wheels -->
#       <left_joint>drivewhl_l_joint</left_joint>
#       <right_joint>drivewhl_r_joint</right_joint>

#       <!-- kinematics -->
#       <wheel_separation>0.4</wheel_separation>
#       <wheel_diameter>0.2</wheel_diameter>

#       <!-- limits -->	
#       <max_wheel_torque>20</max_wheel_torque>
#       <max_wheel_acceleration>1.0</max_wheel_acceleration>

#       <!-- output -->
#       <publish_odom>true</publish_odom>
#       <publish_odom_tf>false</publish_odom_tf>
#       <publish_wheel_tf>true</publish_wheel_tf>

#       <odometry_frame>odom</odometry_frame>
#       <robot_base_frame>base_link</robot_base_frame>
#     </plugin>
#   </gazebo>